#include <windows.h>
#include <tchar.h>
#include <cstring>
#include <wchar.h>
#include <string>

// ID HANDLE //

// Button Handle Ids
#define ID_BUTTON_ONE 1
#define ID_BUTTON_TWO 2
#define ID_BUTTON_THREE 3
#define ID_BUTTON_FOUR 4
#define ID_BUTTON_FIVE 5
#define ID_BUTTON_SIX 6
#define ID_BUTTON_SEVEN 7
#define ID_BUTTON_EIGHT 8
#define ID_BUTTON_NINE 9
#define ID_BUTTON_ZERO 10

#define ID_BUTTON_PLUS 11
#define ID_BUTTON_SUB 12
#define ID_BUTTON_EQUAL 13
#define ID_BUTTON_MULTIPLY 14
#define ID_BUTTON_DIV 15
#define ID_BUTTON_CLEAR 16
#define ID_BUTTON_DELETE 17
#define ID_BUTTON_DECIMAL 18
#define ID_BUTTON_NEGTIVE 19

// Button Size
#define BUTTON_WIDTH 85
#define BUTTON_HEIGHT 85

// WINDOWS // 

// TextField Window
HWND TextField;

// Buttons Window
HWND BUTTON_ONE;
HWND BUTTON_TWO;
HWND BUTTON_THREE;
HWND BUTTON_FOUR;
HWND BUTTON_FIVE;
HWND BUTTON_SIX;
HWND BUTTON_SEVEN;
HWND BUTTON_EIGHT;
HWND BUTTON_NINE;
HWND BUTTON_ZERO;
HWND BUTTON_PLUS;
HWND BUTTON_SUB;
HWND BUTTON_EQUAL;
HWND BUTTON_MULTIPLY;
HWND BUTTON_DIV;
HWND BUTTON_CLEAR;
HWND BUTTON_BACK;
HWND BUTTON_DECIMAL;
HWND BUTTON_NEGTIVE;

// Array of Buttons
HWND BUTTONARRAY[] = { 
	BUTTON_ONE,
	BUTTON_TWO,
	BUTTON_THREE,
	BUTTON_FOUR,
	BUTTON_FIVE,
	BUTTON_SIX,
	BUTTON_SEVEN,
	BUTTON_EIGHT,
	BUTTON_NINE,
	BUTTON_ZERO,
	BUTTON_PLUS,
	BUTTON_SUB,
	BUTTON_EQUAL,
	BUTTON_MULTIPLY,
	BUTTON_DIV,
	BUTTON_CLEAR,
	BUTTON_BACK,
	BUTTON_DECIMAL,
	BUTTON_NEGTIVE 
};

// FONTS // 

// TextField Font
HFONT tFont = CreateFont(-64, 0, 0, 0, 400, 0, 0, 0, ANSI_FIXED_FONT,
	OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS,
	DEFAULT_QUALITY, DEFAULT_PITCH, L"Arial");

// Buttons Font
HFONT bFont = CreateFont(-24, 0, 0, 0, 600, 0, 0, 0, ANSI_FIXED_FONT,
	OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS,
	DEFAULT_QUALITY, DEFAULT_PITCH, L"Segoe UI");

// createButton fanction
void createButton(HWND hwnd)
{
	BUTTONARRAY[0] = CreateButton(ID_BUTTON_ONE, hwnd, 10, 190, BUTTON_WIDTH, BUTTON_HEIGHT, L"1");
	BUTTONARRAY[1] = CreateButton(ID_BUTTON_TWO, hwnd, 100, 190, BUTTON_WIDTH, BUTTON_HEIGHT, L"2");
	BUTTONARRAY[2] = CreateButton(ID_BUTTON_THREE, hwnd, 190, 190, BUTTON_WIDTH, BUTTON_HEIGHT, L"3");
	BUTTONARRAY[3] = CreateButton(ID_BUTTON_FOUR, hwnd, 10, 280, BUTTON_WIDTH, BUTTON_HEIGHT, L"4");
	BUTTONARRAY[4] = CreateButton(ID_BUTTON_FIVE, hwnd, 100, 280, BUTTON_WIDTH, BUTTON_HEIGHT, L"5");
	BUTTONARRAY[5] = CreateButton(ID_BUTTON_SIX, hwnd, 190, 280, BUTTON_WIDTH, BUTTON_HEIGHT, L"6");
	BUTTONARRAY[6] = CreateButton(ID_BUTTON_SEVEN, hwnd, 10, 370, BUTTON_WIDTH, BUTTON_HEIGHT, L"7");
	BUTTONARRAY[7] = CreateButton(ID_BUTTON_EIGHT, hwnd, 100, 370, BUTTON_WIDTH, BUTTON_HEIGHT, L"8");
	BUTTONARRAY[8] = CreateButton(ID_BUTTON_NINE, hwnd, 190, 370, BUTTON_WIDTH, BUTTON_HEIGHT, L"9");
	BUTTONARRAY[9] = CreateButton(ID_BUTTON_ZERO, hwnd, 10, 460, BUTTON_WIDTH, BUTTON_HEIGHT, L"0");
	BUTTONARRAY[10] = CreateButton(ID_BUTTON_PLUS, hwnd, 285, 190, 135, BUTTON_HEIGHT, L"+");
	BUTTONARRAY[11] = CreateButton(ID_BUTTON_SUB, hwnd, 285, 280, 135, BUTTON_HEIGHT, L"-");
	BUTTONARRAY[12] = CreateButton(ID_BUTTON_EQUAL, hwnd, 190, 460, 230, BUTTON_HEIGHT, L"=");
	BUTTONARRAY[13] = CreateButton(ID_BUTTON_MULTIPLY, hwnd, 285, 370, 135, BUTTON_HEIGHT, L"*");
	BUTTONARRAY[15] = CreateButton(ID_BUTTON_CLEAR, hwnd, 190, 95, BUTTON_WIDTH, BUTTON_HEIGHT, L"C");
	BUTTONARRAY[16] = CreateButton(ID_BUTTON_DELETE, hwnd, 285, 95, 135, BUTTON_HEIGHT, L"⌫");
	BUTTONARRAY[17] = CreateButton(ID_BUTTON_DECIMAL, hwnd, 100, 460, BUTTON_WIDTH, BUTTON_HEIGHT, L".");
	BUTTONARRAY[18] = CreateButton(ID_BUTTON_NEGTIVE, hwnd, 10, 95, BUTTON_WIDTH, BUTTON_HEIGHT, L"±");
	BUTTONARRAY[14] = CreateButton(ID_BUTTON_DIV, hwnd, 100, 95, BUTTON_WIDTH, BUTTON_HEIGHT, L"÷");

}

	